// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwI2kzCUIZ2HMZ8TzlmlEKbC3wtAKThc',
    appId: '1:1068658006423:web:e9fc4c36fa4060f8948cd2',
    messagingSenderId: '1068658006423',
    projectId: 'fir-flutter-codelab-6a6e9',
    authDomain: 'fir-flutter-codelab-6a6e9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6a6e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOzKTVmjxh_3Dp2mrfKyw8FeGaHqJ1E5Y',
    appId: '1:1068658006423:android:cc49c416e7c9e3dc948cd2',
    messagingSenderId: '1068658006423',
    projectId: 'fir-flutter-codelab-6a6e9',
    storageBucket: 'fir-flutter-codelab-6a6e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxwlWMPwDMG6usS_5Tp4PcL9X3ZZNPSY',
    appId: '1:1068658006423:ios:9e054146d15a63c9948cd2',
    messagingSenderId: '1068658006423',
    projectId: 'fir-flutter-codelab-6a6e9',
    storageBucket: 'fir-flutter-codelab-6a6e9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxwlWMPwDMG6usS_5Tp4PcL9X3ZZNPSY',
    appId: '1:1068658006423:ios:9e054146d15a63c9948cd2',
    messagingSenderId: '1068658006423',
    projectId: 'fir-flutter-codelab-6a6e9',
    storageBucket: 'fir-flutter-codelab-6a6e9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
